en = {
    "full_lang": "English",
    "in_lang": "en-in",
    "out_lang": "en",
    "title": "Voice assistant",
    "about_text": "App made for script languages laboratory",
    "settings": "Settings",
    "exit": "Exit",
    "file": "File",
    "commands": "Commands",
    "about": "About",
    "help": "Help",
    "push_button": "Push button and say something",
    "previous_command": "Previous command",
    "try_commands": "Try: \"Hello\"\nTry: \"What time is it?\"\nTry: \"Open notepad\"",
    "say_something": "Say something",
    "recognizing": "Recognizing",
    "unable_to_recognize": "I was unable to recognize your voice, try again",
    "all_commands": "Hello\nWhat time is it?\nOpen [app]\nOther commands",
    "language": "Language",
    "username": "Username",
    "restart": "Restart",
    "add": "Add",
    "edit": "Edit",
    "remove": "Remove",
    "save_config": "Save config",
    "name": "Name",
    "enter_app_name": "Enter app name",
    "error": "Error",
    "already_on_list": "is already on list",
    "err_choose_exe": "You have to choose exe file",
    "err_enter_app_name": "You have to enter app name",
    "delete": "Delete",
    "del_confirm1": "Are you sure you want to delete",
    "del_confirm2": "from list?",
    "save_confirm": "Are you sure you want to save changes to config file?",
    "exit_confirm": "If you close without saving, changes will be lost"
}

pl = {
    "full_lang": "Polski",
    "in_lang": "pl-in",
    "out_lang": "pl",
    "title": "Asystent głosowy",
    "about_text": "Aplikacja stworzona na laboratoria z języków skryptowych",
    "settings": "Ustawienia",
    "exit": "Wyjście",
    "file": "Plik",
    "commands": "Polecenia",
    "about": "O aplikacji",
    "help": "Pomoc",
    "push_button": "Naciśnij przycisk i powiedz coś",
    "previous_command": "Poprzednie polecenie",
    "try_commands": "Spróbuj: \"Cześć\"\nSpróbuj: \"Która jest godzina?\"\nSpróbuj: \"Otwórz notatnik\"",
    "say_something": "Powiedz coś",
    "recognizing": "Przetwarzanie",
    "unable_to_recognize": "Nie rozpoznałem co powiedziałeś, spróbuj jeszcze raz",
    "all_commands": "Cześć\nKtóra jest godzina?\nOtwórz [aplikacja]\nPozostałe polecenia",
    "language": "Język",
    "username": "Nazwa użytkownika",
    "restart": "Uruchom ponownie",
    "add": "Dodaj",
    "edit": "Edytuj",
    "remove": "Usuń",
    "save_config": "Zapisz konfigurację",
    "name": "Nazwa",
    "enter_app_name": "Wpisz nazwę aplikacji",
    "error": "Błąd",
    "already_on_list": "jest już na liście",
    "err_choose_exe": "Musisz wybrać plik exe",
    "err_enter_app_name": "Musisz wpisać nazwę aplikacji",
    "delete": "Usuń",
    "del_confirm1": "Jesteś pewien, że chcesz usunąć",
    "del_confirm2": "z listy?",
    "save_confirm": "Jesteś pewien, że chcesz zapisać zmiany do pliku konfiguracyjnego?",
    "exit_confirm": "Jeśli wyjdziesz bez zapisywania, zmiany zostaną utracone"
}

languages = {
    "English": en,
    "Polski": pl
}

languages_short = {
    "en": en,
    "pl": pl
}
